min_sensor_dist: .05
self_see_default_padding: .01
self_see_default_scale: 1.0
self_see_links:
  - name: l_upper_arm_link
    padding: .05
  - name: l_upper_arm_roll_link
    padding: .05
  - name: l_elbow_flex_link
    padding: .05
  - name: l_forearm_link
    padding: .05
  - name: l_forearm_roll_link
    padding: .05
  - name: l_wrist_flex_link
    padding: .05
  - name: l_wrist_roll_link
    padding: .05
  - name: l_gripper_palm_link
    padding: .05
  - name: l_gripper_l_finger_link
    padding: .05
  - name: l_gripper_l_finger_tip_link
    padding: .05
  - name: l_gripper_r_finger_link
    padding: .05
  - name: l_gripper_r_finger_tip_link
    padding: .05
  - name: l_shoulder_pan_link
    padding: .05
  - name: l_shoulder_lift_link
    padding: .05
  - name: r_upper_arm_link
    padding: .05
  - name: r_upper_arm_roll_link
    padding: .05
  - name: r_elbow_flex_link
    padding: .05
  - name: r_forearm_link
    padding: .05
  - name: r_forearm_roll_link
    padding: .05
  - name: r_wrist_flex_link
    padding: .05
  - name: r_wrist_roll_link
    padding: .05
  - name: r_gripper_palm_link
    padding: .05
  - name: r_gripper_l_finger_link
    padding: .05
  - name: r_gripper_l_finger_tip_link
    padding: .05
  - name: r_gripper_r_finger_link
    padding: .05
  - name: r_gripper_r_finger_tip_link
    padding: .05
  - name: r_shoulder_pan_link
    padding: .05
  - name: r_shoulder_lift_link
    padding: .05
  - name: base_link
    padding: .05
